AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda to create new VM instance

Parameters:
  Region:
    Type: String
    Description: Region of resources
    Default: us-west-1
  InstanceType:
    Type: String
    Default: t2.micro
  SshKeyParameter:
    Description: SSH Keypair to login to the instance
    Type: AWS::EC2::KeyPair::KeyName
    Default: fovustest
  SubnetId:
    Description: SSH Keypair to login to the instance
    Type: AWS::EC2::Subnet::Id
    Default: subnet-06c0439c683654068
  Ami:
    Description: AMI to use
    Type: String
    Default: ami-03ededff12e34e59e

Resources:
#  S3UploadBucket:
#    Type: AWS::S3::Bucket
#    Properties:
#      CorsConfiguration:
#        CorsRules:
#          - AllowedHeaders:
#              - "*"
#            AllowedMethods:
#              - GET
#              - PUT
#              - HEAD
#            AllowedOrigins:
#              - "*"
#
#  DDBTable:
#    Type: AWS::DynamoDB::Table
#    Properties:
#      AttributeDefinitions:
#        - AttributeName: id
#          AttributeType: N
#      KeySchema:
#        - AttributeName: id
#          KeyType: HASH
#      BillingMode: PAY_PER_REQUEST
#
#  LambdaIamRole:
#    Type: AWS::IAM::Role
#    Properties:
#      AssumeRolePolicyDocument:
#        Version: '2012-10-17'
#        Statement:
#          - Effect: 'Allow'
#            Principal:
#              Service:
#                - 'lambda.amazonaws.com'
#            Action:
#              - 'sts:AssumeRole'
#      Path: '/'

